import { BookableGroup } from "./@types/bookable.interface";
import { Users } from "./@types/user.interface";

export const usersMock: Users = [
  {
    id: 1,
    name: "John",
    img: "https://randomuser",
    title: "Mr",
    notes: "John notes",
  },
  {
    id: 2,
    name: "Jane",
    img: "https://randomuser",
    title: "Mrs",
    notes: "Jane notes",
  },
  {
    id: 3,
    name: "Jack",
    img: "https://randomuser",
    title: "Mr",
    notes: "Jack notes",
  },
  {
    id: 4,
    name: "Jill",
    img: "https://randomuser",
    title: "Mrs",
    notes: "Jill notes",
  },
  {
    id: 5,
    name: "James",
    img: "https://randomuser",
    title: "Mr",
    notes: "James notes",
  },
  {
    id: 6,
    name: "Judy",
    img: "https://randomuser",
    title: "Mrs",
    notes: "Judy notes",
  },
];

export const bookableMock: BookableGroup = [
  {
    id: 1,
    group: "Rooms",
    title: "Room 1",
    notes: "Room 1 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 2,
    group: "Rooms",
    title: "Room 2",
    notes: "Room 2 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 3,
    group: "Rooms",
    title: "Room 3",
    notes: "Room 3 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 4,
    group: "Courts",
    title: "Court 1",
    notes: "Court 1 notes",
    sessions: [5, 6, 7],
    days: [88, 29, 31],
  },
  {
    id: 5,
    group: "Courts",
    title: "Court 2",
    notes: "Court 2 notes",
    sessions: [8, 9, 31],
    days: [21, 22, 13],
  },
  {
    id: 6,
    group: "Courts",
    title: "Court 3",
    notes: "Court 3 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 7,
    group: "Courts",
    title: "Court 4",
    notes: "Court 4 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 8,
    group: "Courts",
    title: "Court 5",
    notes: "Court 5 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 9,
    group: "Courts",
    title: "Court 6",
    notes: "Court 6 notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 10,
    group: "Kit",
    title: "Projector",
    notes: "Projector notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
  {
    id: 11,
    group: "Kit",
    title: "Wireless Mic",
    notes: "Wireless notes",
    sessions: [1, 2, 3],
    days: [1, 2, 3],
  },
];
